### ISSUE TITLE
[TO-DO] Add multiple new job types

### ISSUE THREAD

**Issue by Picono435** [Picono435/PicoJobs#158]
- [x] FILL | Fill some buckets

- [ ] BREED | Breed random animals

- [x] SHEAR | Shear the sheep

- [ ] DYE | Dye things

- [x] TAME | Tame your animals

- [x] MOVE | Explore the world

- [ ] BREWER | Brew potions

- [x] TRADE | Trade with villagers

- [x] STRIPLOGS | Strip logs
